routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');


Route::resource('rooms', 'RoomController')->middleware('auth');
Route::resource('defects', 'DefectController')->middleware('auth');
Route::resource('defectcategories', 'DefectCategoryController')->middleware('auth');
Route::resource('users', 'UserController')->middleware('auth');
Route::resource('positions', 'PositionController')->middleware('auth');

app/Defect.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Defect extends Model
{

       /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'information', 'room_id', 'defectcategory_id', 'user_id', 'status_id',
    ];


    public function User()
    {
        return $this->belongsTo('App\User');
    }

    public function Room()
    {
        return $this->belongsTo('App\Room');
    }

    public function Status()
    {
        return $this->belongsTo('App\Status');
    }

    public function Comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function DefectCategory()
    {
        return $this->belongsTo('App\Defect_Category', 'defectcategory_id');
    }
/*
    public function getLaststatusAttribute()
    {
        return $this->Status()->orderBy('created_at')->first();
    }
    */
}

app/Http/Controllers/DefectController.php
<?php

namespace App\Http\Controllers;

use App\Defect;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DefectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $defects = \App\Defect::orderBy('updated_at', 'desc')->paginate(15);


        return view('defect.index', ['defects' => $defects]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rooms = \App\Room::all();
        $categories = \App\Defect_Category::all();
        return view('defect.create', ['rooms' => $rooms, 'categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user_id = Auth::user()->id;

    
 
        \App\Defect::create([
          'room_id' => $request->input('rooms'),
          'defectcategory_id'=> $request->input('category'),
          'information'=> $request->input('information'),
          'status_id'=> '1',
          'user_id' => $user_id
        ]);
 
        return redirect('/defects')->with('success', 'Dodano nowe zadanie.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Defect  $defect
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $defect = \App\Defect::find($id);

        return view('defect.show', ['defect' => $defect]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Defect  $defect
     * @return \Illuminate\Http\Response
     */
    public function edit(Defect $defect)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Defect  $defect
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Defect $defect)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Defect  $defect
     * @return \Illuminate\Http\Response
     */
    public function destroy(Defect $defect)
    {
        //
    }
}

resources/views/defect/create.blade.php
@extends('layouts.app')

@section('content')


<div class="row justify-content-center">
    <div class="col-6">

                    <div class="card">
                            <form method="post" action="{{ route('defects.store') }}">
                                    @csrf
                            <div class="card-body">
                                <h4 class="card-title">Dodaj usterkę</h4>
                                <div class="form-group row">
                                    <label for="rooms" class="col-sm-3 text-right control-label col-form-label">Wybierz pokój: </label>
                                    <div class="col-sm-9">
                                    <select name = "rooms" name = "rooms" class="form-control">
                                    @foreach($rooms as $room)
                                            <option value = "{{$room->id}}">{{$room->number}} - {{$room->name}}</option>
                                    @endforeach
                                    </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                        <label for="category" class="col-sm-3 text-right control-label col-form-label">Wybierz kategorie: </label>
                                        <div class="col-sm-9">
                                        <select id = "category" name = "category" class="form-control">
                                        @foreach($categories as $category)
                                                <option value = "{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                        </select>
                                        </div>
                                </div>

                                <div class="form-group row">
                                        <label for="information" class="col-sm-3 text-right control-label col-form-label">Opisz zadanie: </label>
                                        <div class="col-sm-9">
                                        <textarea class="form-control" name="information" rows="3"></textarea>
                                        </div>
                                </div>
                            </div>
                            <div class="border-top">
                                <div class="card-body">
                                    <button type="submit" class="btn btn-primary">Dodaj</button>
                                </div>
                            </div>
                        </form>
                    </div>




</div>

@endsection

resources/views/defect/index.blade.php
@extends('layouts.app')

@section('content')

@foreach ($defects as $defect)

<div class="row justify-content-center">
  <div class="col-12">
      <div class="card">
          <div class="card-body">
              <div class="d-flex flex-row comment-row m-t-0">
              <div class="p-2"><h1><i class="text-{{ $defect->defectcategory->color }} mdi {{ $defect->defectcategory->icon }}"></i></h1></div>
                <div class="comment-text w-100">
                        <div class="m-b-15 font-medium"><h6>#{{ $defect->id }} <span class="{{ $defect->status->color }}">{{ $defect->status->name }}</span></h6></div>
                <span class="m-b-5 d-block">{{ $defect->information }} 
                </span>
                <div class="m-b-15">
                <span class="d-inline m-r-10"><p class="font-weight-bold d-inline">Kategoria: </p><span class="text-{{ $defect->defectcategory->color }}">{{ $defect->defectcategory->name }}</span></span>
                <span class="d-inline m-r-10"><p class="font-weight-bold d-inline">Budynek: </p>A</span>
                <span class="d-inline m-r-10"><p class="font-weight-bold d-inline">Pokój: </p>{{ $defect->room->number }}</span>
                <span class="d-inline m-r-10"><p class="font-weight-bold d-inline">Dodał: </p>{{ $defect->user->name }}</span>
                </div>
                <div class="comment-footer">
                    <span class="text-muted float-right">Data aktualizacji zgłoszenia: {{ $defect->updated_at }}</span> 
                    <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-cyan btn-sm">Otwórz</a>
                    <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-success btn-sm">Zmień status</a>
                    <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-secondary btn-sm">Skomentuj</a>
                    <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-danger btn-sm">Archiwizuj</a>
                    <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-danger btn-sm">Usuń</a>
                </div>
                <span class="float-right badge badge-danger">Wiadomości: {{ $defect->comments()->count() }}</span>
            </div>
              
          </div>
      </div>
  </div>
</div>
</div>
@endforeach

<div class="mx-auto">
    {{ $defects->links() }}
  </div>
@endsection

resources/views/defect/show.blade.php
@extends('layouts.app')

@section('content')

<div class="row justify-content-center">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                    <div class="card-body">
                            <div class="d-flex flex-row comment-row m-t-0">
                                    <div class="p-2"><h1><i class="text-{{ $defect->defectcategory->color }} mdi {{ $defect->defectcategory->icon }}"></i></h1></div>
                              <div class="comment-text w-100">
                              <h6 class="font-medium m-b-10">#{{ $defect->id }} <span class="{{ $defect->status->color }}">{{ $defect->status->name }}</span></h6>
                              <span class="d-block m-b-15">{{ $defect->information }} 
                              </span>
                              <div class="m-b-15">
                                    <span class="d-inline m-r-10"><p class="font-weight-bold d-inline">Kategoria: </p><span class="text-{{ $defect->defectcategory->color }}">{{ $defect->defectcategory->name }}</span></span>
                              <span class="d-block m-t-10"><p class="font-weight-bold d-inline">Budynek: </p>A</span>
                              <span class="d-block m-t-10"><p class="font-weight-bold d-inline">Pokój: </p>{{ $defect->room->number }}</span>
                              <span class="d-block m-t-10"><p class="font-weight-bold d-inline">Dodał: </p>{{ $defect->user->name }}</span>
                              </div>
                              <div class="comment-footer">
                                  <span class="text-muted float-right">Data utworzenia zgłoszenia: {{ $defect->created_at }}</span> 
                                  <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-cyan btn-sm">Otwórz</a>
                                  <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-success btn-sm">Zmień status</a>
                                  <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-secondary btn-sm">Skomentuj</a>
                                  <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-danger btn-sm">Archiwizuj</a>
                                  <a href="{{ URL::to('defects/' . $defect->id) }}" class="btn btn-danger btn-sm">Usuń</a>
                              </div>
              </div>
                
            </div>
        </div>
    </div>
  </div>

  <div class="card">
        <div class="card-body">
            <h4 class="card-title">Komentarze</h4>
        </div>
        <div class="comment-widgets scrollable ps-container ps-theme-default" data-ps-id="3f9fdb42-e6c4-a5a0-6041-6a84ec9af5a1">
            <!-- Comment Row -->

            @foreach ($defect->comments as $comment)

            <div class="comment-row m-t-0">
                <div class="p-2"><img src="../../assets/images/users/1.jpg" alt="user" width="50" class="rounded-circle"></div>
                <div class="comment-text w-100">
                <div class="m-b-15 font-medium"><h6><span class='{{ $comment->commenttype->color }}'>{{ $comment->commenttype->name }}</span></h6> </div>
                    
                    <h6 class="font-medium">{{ $comment->user->name }}</h6>
                    
                    @if ($comment->commenttype->id == 1)
                    <span class="m-b-15 d-block">{{ $comment->information }} </span>
                    @else
                    <span class="m-b-15 d-block">Zmienił status na <span class= '{{ $comment->status->color}}'>{{ $comment->status->name}} </span></span>
                    <span class="m-b-15 d-block">{{ $comment->information }} </span>

                    @endif
                    <div class="comment-footer">
                        <span class="text-muted float-right">{{ $comment->created_at }}</span> 
                    </div>
                </div>
            </div>

            @endforeach

        </div>
    </div>

@endsection